jobs:
  - name: assemble
    type: runSh
    steps:
     - IN: ryvr_master_rSync
     - IN: ryvr_master
     - TASK: 
       - script: ls && ls ./IN && ./IN/mexec-repo/gitRepo/gradlew assemble --info

  - name: unitTest
    type: runSh
    steps:
     - IN: assemble
     - IN: ryvr_master
     - TASK: 
       - script: ls && ls ./IN && ./gradlew unitTest -PtestOutputDir=shippable/testresults -x jacocoTestReport --info 
       