server:
  ssl:
    key-store: keystore.jks
  servlet-path: /

spring:
  application:
    name: ryvr
        
server.tomcat.access-log-enabled: true
      
      
au.com.mountainpass.ryvr:
    ssl:
        hostname: localhost
      