server:
    port: 8443
    servlet-path: /

spring:
  application:
    name: ryvr
       
    
security:
  user:
    name: 'user'
    password: 'password'
    
        
server.tomcat.access-log-enabled: true
      
      
au.com.mountainpass.ryvr:
    ssl:
        hostname: localhost
      