server:
  port: 8443
  compression.enabled: true
  use-forward-headers: true
  ssl:
    key-store: keystore.jks
    key-store-password: secret
    key-password: secret
    key-alias: selfSigned
  servlet-path: /
  undertow:
    buffer-size: 8388608
    direct-buffers: true
    io-threads: 1
    worker-threads: 1
    accesslog:
      enabled: true

spring:
  application:
    name: ryvr
  resources:
    cache-period: 2592000
    chain.strategy.content.enabled: true


security:
  user:
    name: user
    password: password
    role: USER
  
au.com.mountainpass.ryvr:
  ssl:
    hostname: localhost
    genCert: selfSigned
#  data-sources:
#    - url: jdbc:mysql://localhost/test_db?serverTimezone=UTC
#      username: dbuser
#      password: dbpass
#      ryvrs:
#        transactions:
#          page-size: 128
#          query: select `id`, `account`, `description`, `amount` from `transactions` ORDER BY `id` ASC
  cache:
    archive-page-max-age: 30
    archive-page-max-age-unit: DAYS
    current-page-max-age: 1
    current-page-max-age-unit: SECONDS
    