server:
  port: 8443
  ssl:
    key-store: keystore.jks
    key-store-password: secret
    key-password: secret
    key-alias: selfSigned
  servlet-path: /
#  undertow:
#    buffer-size: 8388608
#    direct-buffers: true
#    io-threads: 1
#    worker-threads: 1

spring:
  application:
    name: ryvr
  resources:
    cache-period: 2592000

server.undertow.accesslog.enabled: true

au.com.mountainpass.ryvr:
  ssl:
    hostname: localhost
    genCert: selfSigned
  data-sources:
    - url: jdbc:mysql://localhost?serverTimezone=UTC
      username: dbuser
      password: dbpass
      ryvrs:
        transactions:
          page-size: 128
          catalog: test_db
          table: TRANSACTIONS
          ordered-by: ID
  cache:
    archive-page-max-age: 30
    archive-page-max-age-unit: DAYS
    current-page-max-age: 1000
    current-page-max-age-unit: MILLISECONDS
    