# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2
jobs:
  assemble:
    <<: *defaults

    steps:      
      - checkout
      - restore_cache:
          keys:
          - gradle-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - gradle-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew assemble compileTestJava
      - run: pwd
      - run: ls
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build/classes/main
            - build/classes/test
            - build/distributions
            - build/resources/main
            - build/resources/test
            

  testRyvrTests_Integration_Java_H2Local:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - gradle-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo/build
      - run: ls
      - run: ls ~/repo/build
      - run: ./gradlew testRyvrTests_Integration_Java_H2Local
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/repo
          # Must be relative path from root
          paths:
            - build/coverage-results-RyvrTests_Integration_Java_H2Local
            - build/test-results/testRyvrTests_Integration_Java_H2Local
            - build/test-results-testRyvrTests_Integration_Java_H2Local

  testRyvrTests_Integration_Rest_H2Local:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - gradle-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo/build
      - run: ls
      - run: ls ~/repo/build
      - run: ./gradlew testRyvrTests_Integration_Rest_H2Local
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/repo
          # Must be relative path from root
          paths:
            - build/coverage-results-RyvrTests_Integration_Rest_H2Local
            - build/test-results/testRyvrTests_Integration_Rest_H2Local
            - build/test-results-testRyvrTests_Integration_Rest_H2Local

  jacocoTestReport:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - gradle-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo/build
      - run: ./gradlew jacocoTestReport
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/repo
          # Must be relative path from root
          paths:
            - build/coverage-results
    
workflows:
  version: 2
  build_and_test:
    jobs:
      - assemble
      - testRyvrTests_Integration_Java_H2Local:
          requires:
            - assemble
      - testRyvrTests_Integration_Rest_H2Local:
          requires:
            - assemble
      - jacocoTestReport:
          requires:
            - testRyvrTests_Integration_Java_H2Local
            - testRyvrTests_Integration_Rest_H2Local
