# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2
jobs:
  assemble:
    <<: *defaults

    steps:      
      - checkout
      - restore_cache:
          keys:
          - gradle-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - gradle-dependencies-
      - run: ./gradlew downloadDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew assemble compileTestJava
      - store_artifacts:
          path: build/distributions
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build/classes/main
            - build/classes/test
            - build/distributions
            - build/resources/main
            - build/resources/test
            

  testRyvrTests_Integration_Java_H2Local:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - gradle-dependencies-
      - run: ./gradlew downloadDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo
      - run: ./gradlew testRyvrTests_Integration_Java_H2Local
      - store_test_results:
          path: build/test-results/testRyvrTests_Integration_Java_H2Local
      - store_artifacts:
          path: build/test-results/testRyvrTests_Integration_Java_H2Local
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/repo
          # Must be relative path from root
          paths:
            - build/coverage-results-RyvrTests_Integration_Java_H2Local
            - build/test-results/testRyvrTests_Integration_Java_H2Local

  testRyvrTests_Integration_Rest_H2Local:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - gradle-dependencies-
      - run: ./gradlew downloadDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo
      - run: ./gradlew testRyvrTests_Integration_Rest_H2Local
      - store_test_results:
          path: build/test-results/testRyvrTests_Integration_Rest_H2Local
      - store_artifacts:
          path: build/test-results/testRyvrTests_Integration_Rest_H2Local
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/repo
          # Must be relative path from root
          paths:
            - build/coverage-results-RyvrTests_Integration_Rest_H2Local
            - build/test-results/testRyvrTests_Integration_Rest_H2Local

  testRyvrTests_Integration_Rest_MySqlLocal:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk
      - image: mysql:8.0.2
        environment:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: dbpass
          MYSQL_USER: dbuser
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_HOST: "%"
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - gradle-dependencies-
      - run: ./gradlew downloadDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo
      - run: ./gradlew testRyvrTests_Integration_Rest_MySqlLocal
      - store_test_results:
          path: build/test-results/testRyvrTests_Integration_Rest_MySqlLocal
      - store_artifacts:
          path: build/test-results/testRyvrTests_Integration_Rest_MySqlLocal
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/repo
          # Must be relative path from root
          paths:
            - build/coverage-results-RyvrTests_Integration_Rest_MySqlLocal
            - build/test-results/testRyvrTests_Integration_Rest_MySqlLocal

  testRyvrTests_Integration_Ui_H2Local_ChromeSauceLabs:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - gradle-dependencies-
      - run: ./gradlew downloadDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo
      - run: 
          command: ./gradlew testRyvrTests_Integration_Ui_H2Local_ChromeSauceLabs -PSAUCE_LABS_USERNAME=$SAUCE_LABS_USERNAME -PSAUCE_LABS_KEY=$SAUCE_LABS_KEY --info
          no_output_timeout: 1200
      - store_test_results:
          path: build/test-results/testRyvrTests_Integration_Ui_H2Local_ChromeSauceLabs
      - store_artifacts:
          path: build/test-results/testRyvrTests_Integration_Ui_H2Local_ChromeSauceLabs
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/repo
          # Must be relative path from root
          paths:
            - build/coverage-results-RyvrTests_Integration_Ui_H2Local_ChromeSauceLabs
            - build/test-results/testRyvrTests_Integration_Ui_H2Local_ChromeSauceLabs

  jacocoTestReport:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - gradle-dependencies-
      - run: ./gradlew downloadDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo
      - run: ls ~/repo/build
      - run: ls ~/repo/build/test-results/
      - run: ls ~/repo/build/coverage-results-*
      - run: ./gradlew jacocoTestReport --info
      - run: ls -l build/coverage-results/jacoco
      - run: ./gradlew testRyvrTests_Coverage --info
      - store_test_results:
          path: build/test-results/testRyvrTests_Coverage
      - store_artifacts:
          path: build/test-results/testRyvrTests_Coverage
          path: build/coverage-results/jacoco/html
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/repo
          # Must be relative path from root
          paths:
            - build/coverage-results
            - build/test-results/testRyvrTests_Coverage
    
workflows:
  version: 2
  build_and_test:
    jobs:
      - assemble
      - testRyvrTests_Integration_Java_H2Local:
          requires:
            - assemble
      - testRyvrTests_Integration_Rest_H2Local:
          requires:
            - assemble
      - testRyvrTests_Integration_Rest_MySqlLocal:
          requires:
            - assemble
      - testRyvrTests_Integration_Ui_H2Local_ChromeSauceLabs:
          requires:
            - assemble
          context: org-global
      - jacocoTestReport:
          requires:
            - testRyvrTests_Integration_Java_H2Local
            - testRyvrTests_Integration_Rest_H2Local
            - testRyvrTests_Integration_Rest_MySqlLocal
            - testRyvrTests_Integration_Ui_H2Local_ChromeSauceLabs
